### ISSUE TITLE
panicked at 'attempt to subtract with overflow', src/sink/send.rs:222

### ISSUE THREAD

**Issue by Whyrl35** [runabove/beamium#38]
There is a issue on line 222 of send.rs

Jun 22 06:12:03.853 INFO starting
Jun 22 06:12:03.855 INFO /var/log/beamium
Jun 22 06:12:03.856 INFO spawning scrapers
Jun 22 06:12:03.856 INFO spawning router
Jun 22 06:12:03.856 INFO spawning sinks
Jun 22 06:12:03.857 INFO started
Jun 22 06:12:04.154 INFO post success - 6345, sink: warp10metrics
Jun 22 06:12:21.844 INFO fetch success, scraper: noderig
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/sink/send.rs:222
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jun 22 06:12:46.207 INFO route success - 972298
Jun 22 06:12:51.171 INFO fetch success, scraper: noderig
Jun 22 06:13:04.181 INFO fetch success, scraper: noderig
Jun 22 06:13:11.232 INFO route success - 484352

When the thread crash, beamium can't send data anymore to its sink

**Comment by Whyrl35** [comment]
corrected in commit : 4cfcb45b09ca2b2944ac569564de219cf7540127
